# Generated by Django 4.2.4 on 2023-08-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_author_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.CharField(default='test', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
