# Generated by Django 4.2.4 on 2023-08-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_author_slug_alter_book_slug_alter_genre_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
