# Generated by Django 4.2.4 on 2023-08-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
